name: Release Build

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js 14.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1

      - name: Allow access to private Amplience repos
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" >> .npmrc

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
      - name: Inject Ref Slug
        uses: rlespinasse/github-slug-action@v2.x
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: build
          DEST_DIR: 'main'

      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,ref,took
          username: FTF
          icon_emoji: ':soon-chris:'
          text: '*Release build* (${{ github.run_number }}): https://dc-extension-kanban-board.s3-eu-west-1.amazonaws.com/main/index.html'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Echo build
        run: echo https://dc-extension-kanban-board.s3-eu-west-1.amazonaws.com/main/index.html
