# This is a basic workflow to help you get started with Actions

name: QA Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, release/**, feature/** ]
  pull_request:
    branches: [ main, release/**, feature/** ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node.js 12.19.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.19.0

    - name: Yarn Install
      run: yarn install --frozen-lockfile
    
    - name: Build 
      run: yarn run build
    - name: Inject Ref Slug 
      uses: rlespinasse/github-slug-action@v2.x
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: build
        DEST_DIR: '${{ env.GITHUB_REF_SLUG }}-${{ env.github.run_number }}'
