# This is a basic workflow to help you get started with Actions

name: QA Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main, release/**, feature/**]
  pull_request:
    branches: [main, release/**, feature/**]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js 12.19.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.19.0

      - name: Allow access to private Amplience repos
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" >> .npmrc

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
      - name: Inject Ref Slug
        uses: rlespinasse/github-slug-action@v2.x
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: build
          DEST_DIR: '${{ env.GITHUB_REF_SLUG }}-${{ github.run_number }}'

      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,ref,took
          username: FTF
          icon_emoji: ':mike-approves:'
          text: 'Latest build: ${{ env.GITHUB_REF_SLUG }}-${{ github.run_number }} https://dc-extension-kanban-board.s3-eu-west-1.amazonaws.com/${{ env.GITHUB_REF_SLUG }}-${{ github.run_number }}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
